In [27]:
### 1) Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

import numpy as np
np.random.randn(25)

array([ 0.32022555,  0.3245324 ,  0.50231645, -0.43374066,  1.89437957,
        1.06782463,  0.32990683, -0.61759963, -0.21708353,  0.84085552,
        1.33330146,  0.94869335,  0.5614153 ,  0.50169541, -2.06108424,
       -1.4342271 , -0.23063178, -1.32189693,  0.4691527 , -0.45375407,
        0.0399567 , -0.48095098,  0.23359058,  0.3216457 , -0.06822314])

In [33]:
### 2) Create a random vector of size 30 and find the mean value.

np.random.seed(7)
a = np.random.randint(low=0,high=100,size=(30))

np.mean(a)
a.mean()

np.random.randint(low=0,high=100,size=(30)).mean()

51.63333333333333

In [44]:
### 3) Insert 1 to 100 numbers in a NumPy array and reshape it to 10*10 matrix.
a = np.arange(1,101).reshape((10,-1))
a.shape

(10, 10)

In [39]:
help(np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

In [50]:
### 4) Create a 10x10 array with random values and find the minimum and maximum values.
np.random.seed(42)
a = np.random.randint(low=0,high=101,size=(10,10))
print("Minimum value of the array :{}".format(a.min()))
print("Maximum value of the array :{}".format(a.max()))

Minimum value of the array :1
Maximum value of the array :100


In [51]:
### 5) Find Dot product of two arrays

f = np.array([1,2])
g = np.array([4,5])

np.dot(f,g)

14

In [54]:
### 6) Concatenate following arrays along axis=0

x=np.array([[1,2],
            [3,4]])
y=np.array([[5,6]])

np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
### 7) How to get the common items between two python NumPy arrays?

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [56]:
### 8) Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])

np.sort(arr)


array([ 1,  2,  3,  4,  5,  7,  8, 10])

## Numpy upcasting

In [2]:
import numpy as np
list1 = [12,34,54,"Hello",0.97,None]

arr = np.array(list1)
arr

array([12, 34, 54, 'Hello', 0.97, None], dtype=object)

In [3]:
a = np.array([1.2,3.4,5.6])
print(a.dtype)

float64


In [4]:
b = np.array([1,2,3])
print(b.dtype)

int32


In [5]:
c = np.array(["hi","hello","fine"])
print(c.dtype)

<U5


In [7]:
d = np.concatenate((a,b,c),axis=0)
d

array(['1.2', '3.4', '5.6', '1', '2', '3', 'hi', 'hello', 'fine'],
      dtype='<U32')

In [66]:
print(d.dtype)

<U32
