# The Difference Between Copy and View


In [ ]:
The main difference between a copy and a view of an array is that the copy is a new array, and 
the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and
any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and
any changes made to the original array will affect the view.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
# The view SHOULD be affected by the changes made to the original array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Check if Array Owns it's Data


In [ ]:
Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Get the Shape of an Array


In [ ]:
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [7]:
import numpy as np

arr= np.array([[1,2,3,5],[23,334,6,7]])
arr_1= np.array([1,2,3,5])
print(arr.shape)
print(arr_1.shape)

(2, 4)
(4,)


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping

In [ ]:
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

## Reshape From 1-D to 2-D


In [11]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

# here 3 represent no. of rows, and 4 reprensent no. of column

reshape_arr= arr.reshape(3,4)

reshape_arr_base= arr.reshape(3,4).base
print(reshape_arr)
print(reshape_arr_base)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Reshape From 1-D to 3-D


In [10]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

reshape_arr= arr.reshape(3,2,2)
print(reshape_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
(will raise an error):

# Unknown Dimension

In [ ]:
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [13]:
import numpy as np 

arr = np.array([1,2,3,4,5,6,7,8])
reshape_arr= arr.reshape(2,2,-1)

# Convert 1D array with 8 elements to 3D array with 2x2 elements:

print(reshape_arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [ ]:
Note: There are a lot of functions for changing the shapes of arrays in numpy flatten,
    ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. 
    These fall under Intermediate to Advanced section of numpy.