# Creating arrays

In [10]:
import numpy as np

# dir(np)

In [7]:
import numpy as np

# help(np)

In [3]:
import numpy as np

arr=np.array([1,3,4])
print(arr)

[1 3 4]


In [ ]:
# dimensons in array
# Dimension in array is one level of array debth (nested arrays)
# Nested array: are arrays that have arrays as their elements

In [4]:
# 0-D Arrays
# 0-D arrays, or Scalers, are the elemets in an array. Each values in an array is a 0-D array

import numpy as np

arr = np.array(33)

print(arr)

33


In [ ]:
1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
These are the most common and basic arrays.

In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

In [10]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.


In [11]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


## Check Number of Dimensions?

In [12]:
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


# check shape of array

In [4]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


### length of array

In [18]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


# print(len(a))   -- this len(a) gives an error 
print(len(b))
print(len(c))
print(len(d))
print(d)

5
4
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Size of an array and data types

In [34]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5],dtype=float)
c = np.array([[1, 2, 3], [4, 5, 6],[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(a.size)
print(b.size)
print(c.size)
print(d.size)

print(a.dtype)
print(b.dtype)

print(b.dtype.name)






1
5
12
12
int32
float64
float64
