In [ ]:
Resources from w3 School
https://www.w3schools.com/python/numpy/default.asp
    

# Iterating loop.

In [ ]:
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

# 1D Array

In [1]:
import numpy as np

arr= np.array([1,2,3,4,5,6])

for i in arr:
    print(i)

1
2
3
4
5
6


## Getting values from 2D Array

In [26]:
import numpy as np

arr= np.array([[1,2,3,4,5,6],[10,11,13,14,16,17]])

for i in arr:
    print(i)

[1 2 3 4 5 6]
[10 11 13 14 16 17]


In [28]:
# select no in this array 

import numpy as np

arr= np.array([[1,2,3,4,5,6],[10,11,13,14,16,17]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
10
11
13
14
16
17


## Getting values from 3D Array

In [29]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [31]:
# select particular value from 3d array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [ ]:
The function nditer() is a helping function that can be used from very basic to very advanced iterations.
It solves some basic issues which we face in iteration, lets go through it with examples.

In [41]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
data_store= []
for x in np.nditer(arr):
    data_store.append(x)
    
print(data_store)

print(data_store[1]+data_store[2])b

[array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8)]
5


## Iterating Array With Different Data Types


In [ ]:
** use op_dtypes argument and pass it the expected datatype

NumPy does not change the data type of the element in-place (where the element is in array) so
it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer()
we pass flags=['buffered']

In [45]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
      print(x)

b'1'
b'2'
b'3'


# Iterating With Different Step Size


In [46]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate()


In [ ]:
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, 
the ndenumerate() method can be used for those usecases.

In [48]:
# Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([4, 5, 6])

for idx, x in np.ndenumerate(arr):
      print(idx, x)

(0,) 4
(1,) 5
(2,) 6


In [49]:
# Enumerate on following 2D array's elements:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
      print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
