# Joining NumPy Arrays


In [ ]:
Joining means putting contents of two or more arrays in a single array.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis.
If axis is not explicitly passed, it is taken as 0.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
# Join two 2-D arrays along rows (axis=1):
    
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [3]:
# Join two 2-D arrays along rows (axis=0):
    
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Joining Arrays Using Stack Functions


In [ ]:
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0

In [4]:
# axix =1
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
# axix =0
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr)


[[1 2 3]
 [4 5 6]]


### Stacking Along Rows


In [6]:
# NumPy provides a helper function: hstack() to stack along rows.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [7]:
# NumPy provides a helper function: vstack()  to stack along columns.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


#### NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

# Splitting NumPy Arrays


In [ ]:
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])
split_arr = np.array_split(arr,3)
print(split_arr)

# print seperate values in split values

print(split_arr[0])
print(split_arr[1])
print(split_arr[2])

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]
[1 2 3 4]
[5 6 7]
[ 8  9 10]


In [ ]:
An alternate solution is using hsplit() opposite of hstack()
Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

In [12]:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays


In [ ]:
search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

# print index position of 4 in array
print(x)

# print values at even index
y = np.where(arr%2 == 0)
print(y)

# print values at odd index 
z = np.where(arr%2 == 1)
print(z)

## Search Sorted


In [ ]:
There is a method called searchsorted() which performs a binary search in the array, and
returns the index where the specified value would be inserted to maintain the search order.



In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.searchsorted(arr,4)

print( x)

3


In [19]:
# Search From the Right Side
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [22]:
# Multiple Values

import numpy as np 

arr= np.array([12,3,4,5,6,7,8])

short_arr= np.searchsorted(arr,[3,4,5])
print(short_arr)

short_arr= np.searchsorted(arr,[51,22])
print(short_arr)

[0 2 3]
[7 7]


## NumPy Sorting Arrays


In [ ]:
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, 
like numeric or alphabetical, ascending or descending.b

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [24]:
import numpy as np

# array of intigers
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

# array of string 
arr_string = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr_string))

# boolean expresson
arr = np.array([True, False, True])


[0 1 2 3]
['apple' 'banana' 'cherry']


## Filtering Arrays

In [ ]:
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

In [25]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [26]:
# Create a filter array that will return only values higher than 42:


import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
    else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
