Use numpy to generate array of 25 random numbers sampled from a standard normal distribution


In [1]:
import numpy as np
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-0.80334634  0.44896614  0.16519128  0.1225998   0.74874967 -0.5401356
  0.51505251  0.02496682 -0.50137623  0.92766706 -0.54368952  0.31721949
 -2.16632978  0.12812543 -1.26637748]


Create a random vector of size 30 and find the mean value.


In [4]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)

print("Mean is:")
print(x.mean())

Original array:
[0.84136735 0.64593263 0.97403758 0.11163619 0.99894641 0.57181147
 0.43043431 0.39711599 0.6218537  0.58003165]
Mean is:
0.6173167276393494


Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.


In [9]:
import numpy as np

arr= np.array([ i for i in range(1,101) ])

arr.reshape(10,10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

Create a 10x10 array with random values and find the minimum and maximum values.

In [21]:
import numpy as np 

arr= np.random.random((10,10))

print(arr)

arr_min, arr_max = arr.min(),arr.max()

print('Max and min values are',arr_min, arr_max )

[[0.28243295 0.24499445 0.18974263 0.7139072  0.39990749 0.06985147
  0.08228287 0.75683866 0.03198469 0.21094434]
 [0.35753229 0.94254836 0.92078936 0.01712707 0.36058539 0.75432823
  0.03968382 0.09626355 0.21380466 0.43352581]
 [0.0426934  0.36319992 0.7487559  0.40727614 0.49494867 0.13095673
  0.39570482 0.48397173 0.67117723 0.58752531]
 [0.09755811 0.87657048 0.7845727  0.37135816 0.20007828 0.18349149
  0.98782115 0.98632936 0.51460456 0.77672423]
 [0.99769042 0.97454042 0.03313794 0.09737428 0.46546628 0.71539591
  0.38695454 0.19530073 0.88461608 0.14605027]
 [0.91991599 0.39933614 0.79566992 0.95860419 0.5600077  0.39819245
  0.3704021  0.21217019 0.4439061  0.03467425]
 [0.45323519 0.97783463 0.50283797 0.74374406 0.6738309  0.5567843
  0.43144727 0.59782922 0.01038406 0.15037946]
 [0.82042728 0.88255942 0.82387548 0.29403453 0.65753948 0.36878663
  0.74388919 0.04516837 0.15163201 0.00404315]
 [0.21679344 0.30371123 0.6945912  0.72805971 0.69472958 0.69137257
  0.39532666 

Find Dot product of two arrays

Find Dot product of two arrays

f = np.array([1,2])

g = np.array([4,5])

In [22]:
import numpy as np

f = np.array([1,2])

g = np.array([4,5])

print(np.dot(f,g))

14


Concatenate following arrays along axis=0

In [24]:

import numpy as np

x=np.array([[1,2],[3,4]])

y=np.array([[5,6]])

np.concatenate((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

How to get the common items between two python numpy arrays?


In [25]:
import numpy as np


a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

Sort the numpy array:

arr = np.array([10,5,8,4,7,2,3,1])

In [35]:
import numpy as np

arr = np.array([10,5,8,4,7,2,3,1])

print(np.sort(arr))

[ 1  2  3  4  5  7  8 10]
